export default function AboutPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-10 space-y-14">
      {/* HEADER */}
      <header className="space-y-4">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
          About Legal Meter
          <span className="block text-base sm:text-lg font-medium text-slate-600 mt-1">
            Simple, rule-based compliance tools for India
          </span>
        </h1>

        <div className="inline-flex items-center rounded-full bg-indigo-50 px-4 py-1.5 text-xs font-semibold text-indigo-700 border border-indigo-200">
          Built for freelancers, startups & small businesses in India
        </div>
      </header>

      {/* INTRO */}
      <section className="space-y-4">
        <p className="text-sm leading-relaxed text-slate-700">
          Legal Meter is an India-focused legal and compliance calculator
          platform designed to help freelancers, startups, and small businesses
          quickly understand their tax and labour law obligations. We convert
          complex government rules into simple, easy-to-use, rule-based tools
          that deliver clear answers in seconds.
        </p>

        <p className="text-sm leading-relaxed text-slate-700">
          Instead of long articles or confusing legal language, Legal Meter
          focuses on practical decision-making — helping users answer questions
          like whether GST registration is required, how much professional tax
          applies, or whether Shop & Establishment Act registration is
          mandatory.
        </p>
      </section>

      {/* WHAT WE DO */}
      <section className="space-y-6">
        <h2 className="text-xl font-semibold text-slate-900">
          What Legal Meter Does
        </h2>

        <ul className="space-y-3 text-sm text-slate-700 list-disc pl-5">
          <li>
            Provides accurate, rule-based calculators for Indian tax and labour
            law compliance.
          </li>
          <li>
            Explains eligibility, thresholds, and legal triggers in plain,
            understandable language.
          </li>
          <li>
            Helps users make informed compliance decisions without legal jargon.
          </li>
          <li>
            Updates tools regularly to reflect changes in Indian government and
            state-level rules.
          </li>
        </ul>
      </section>

      {/* WHAT WE DON’T DO */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-slate-900">
          What Legal Meter Does Not Do
        </h2>

        <p className="text-sm leading-relaxed text-slate-700">
          Legal Meter does not provide legal advice, tax filing services, or
          professional consultancy. All results generated by our calculators are
          indicative estimates based on publicly available rules and should not
          be treated as a substitute for advice from a qualified professional
          such as a Chartered Accountant or lawyer.
        </p>
      </section>

      {/* WHY LEGAL METER */}
      <section className="space-y-6">
        <h2 className="text-xl font-semibold text-slate-900">
          Why Legal Meter Exists
        </h2>

        <p className="text-sm leading-relaxed text-slate-700">
          Many Indian freelancers and small businesses struggle with compliance
          because government rules are scattered across multiple websites,
          written in complex language, and vary by state. Legal Meter was built
          to bridge this gap by offering a single, reliable place to understand
          core compliance requirements quickly.
        </p>

        <p className="text-sm leading-relaxed text-slate-700">
          Our goal is not to replace professionals, but to help users reach
          clarity faster — so they know when compliance applies and when it
          doesn’t.
        </p>
      </section>

      {/* TRUST & ACCURACY */}
      <section className="space-y-6">
        <h2 className="text-xl font-semibold text-slate-900">
          Accuracy, Trust & Transparency
        </h2>

        <ul className="space-y-3 text-sm text-slate-700 list-disc pl-5">
          <li>
            All calculators are built using current Indian central and
            state-level rules.
          </li>
          <li>Tools are updated periodically to reflect regulatory changes.</li>
          <li>Each calculator clearly explains the logic behind the result.</li>
          <li>
            Disclaimer and “last updated” information are displayed openly.
          </li>
        </ul>
      </section>

      {/* WHO IT'S FOR */}
      <section className="space-y-6">
        <h2 className="text-xl font-semibold text-slate-900">
          Who Legal Meter Is For
        </h2>

        <ul className="space-y-3 text-sm text-slate-700 list-disc pl-5">
          <li>Freelancers and independent professionals</li>
          <li>Startup founders and early-stage businesses</li>
          <li>Small shop owners and MSMEs</li>
          <li>HR teams and employers</li>
          <li>Anyone seeking clarity on Indian compliance rules</li>
        </ul>
      </section>

      {/* FOOTER META */}
      <footer className="border-t pt-6 text-xs text-slate-500 flex flex-col sm:flex-row sm:justify-between gap-3">
        <span>Legal Meter India</span>
        <span>Last updated: January 2026</span>
      </footer>
    </main>
  );
}
